site_name: Trust & Thread
site_description: Zero‑Bloat, Edge‑First learning hub
repo_url: ''
repo_name: ''
theme:
  name: material
  palette:
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: "Fira Code"
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
  language: en
  logo: assets/logo.png
extra_css:
  - assets/custom.css
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
